#!/bin/bash
cd /home/mi/kingpfogel/dev/bachelor_test/build
cmake /home/mi/kingpfogel/dev/bachelor_test/unit/ -DCMAKE_CXX_COMPILER=/home/mi/kingpfogel/miniconda3/bin/g++ -DCMAKE_PREFIX_PATH="$HOME/dev/seqan/util/cmake" -DSEQAN_INCLUDE_PATH="$HOME/dev/seqan/include" -DCMAKE_BUILD_TYPE=RELEASE -DSDSL_INCLUDE_DIRS="../../sdsl-lite/include/" -DCMAKE_CXX_FLAGS="-O3 -march=native -std=c++17"
cd /home/mi/kingpfogel/dev/bachelor_test/build
make
